def decode(message):
    message = message.lower()
    message = message.replace("a","z")
    message = message.replace("b","y")
    message = message.replace("c","x")
    message = message.replace("d","w")
    message = message.replace("e","v")
    message = message.replace("f","u")
    message = message.replace("g","t")
    message = message.replace("h","s")
    message = message.replace("i","r")
    message = message.replace("j","q")
    message = message.replace("k","p")
    message = message.replace("l","o")
    message = message.replace("m","n")
    message = message.replace("n","m")
    message = message.replace("o","l")
    message = message.replace("p","k")
    message = message.replace("q","j")
    message = message.replace("r","i")
    message = message.replace("s","h")
    message = message.replace("t","g")
    message = message.replace("u","f")
    message = message.replace("v","e")
    message = message.replace("w","d")
    message = message.replace("x","c")
    message = message.replace("y","b")
    message = message.replace("z","a")
   
   return 

